src/routes.ts
src/service.ts

I. Context
No HTTP request handler is present in the current code
II. Enhancements
We have added a new http request response handler that : 
- throw error data to the main route catch if response not ok
- return the right data (json or text) depending on the content-type response header
III. Examples 
Here are some examples of error we get with the handler : 
One of the API called is not responding : 
Example n°1 : 
{
"date": "2023-04-27T15:39:27.435Z",
"status": "error",
"message": "Deposit API - fetch failed",
"response": {}
}
Example n°2 : 
{
"date": "2023-04-27T15:41:08.861Z",
"status": "error",
"message": "Ban legacy API - fetch failed",
"response": {}
}
Error data returned by one of the API used : 
Example n°1 : 
{
"date": "2023-04-27T15:22:59.989Z",
"status": "error",
"message": …

Added http request response handler

---

src/bal-converter/index.ts
src/bal-converter/utils.ts
src/ban-api/index.ts
src/types/ban-types.d.ts

This PR aims to rename schema fields for address and common toponym to fit english standards. As a consequence, here are the new schemas : 
1. address schema : 
```
id: BanID; // identifiant unique de l'adresse
districtID: DistrictInseeID; // code INSEE de la commune
commonToponymID: BanCommonTopoID; // identifiant unique de la voie
number: number; // numéro de l'adresse
suffix?: string;
positions: Position[]; // positions géographiques de l'adresse
parcels?: string[]; // parcelles cadastrales de l'adresse // TODO: Verrifier que les parcelles ne soit pas par position et non par adresse
certified?: boolean;
updateDate: DateISO8601; // date de mise à jour de l'adresse
```
2. commonToponym schema : 
```
id: BanCommonTopoID; // identifiant unique de la voie
districtID: DistrictInseeID; // …
```

Updated address and toponym schema to fit ban-plateforme schemas

---

docker-compose.yml

Variable `IDEFIX_BANID_DISTRICTS` is not used anymore. As a consequence, we need to delete it from the docker compose file.

Deleted useless variable in docker-compose file

---

data-mock/adresses-21286_cocorico.json
data-mock/adresses-21286_cocorico.legacy.json
data-mock/adresses-21286_cocorico.partial.json
src/bal-converter/helpers/__mocks__/fake-data.ts
src/bal-converter/helpers/__snapshots__/bal-addr-to-ban-addr.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-json-legacy-to-bal-json.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-position-type-to-ban-position-type.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-topo-to-ban-topo.test.ts.snap
src/bal-converter/helpers/__snapshots__/csv-bal-to-json-bal.test.ts.snap
src/bal-converter/helpers/__snapshots__/digest-ids-from-bal-uids.test.ts.snap
src/bal-converter/helpers/bal-addr-to-ban-addr.test.ts
src/bal-converter/helpers/bal-addr-to-ban-addr.ts
src/bal-converter/helpers/bal-position-type-to-ban-position-type.test.ts
src/bal-converter/helpers/bal-position-type-to-ban-position-type.ts
src/bal-converter/helpers/bal-topo-to-ban-topo.test.ts
src/bal-converter/helpers/bal-topo-to-ban-topo.ts
src/bal-converter/helpers/csv-bal-to-json-bal.ts
src/bal-converter/helpers/digest-ids-from-bal-uids.test.ts
src/bal-converter/helpers/position-type-dictionary.json
src/types/ban-types.d.ts
tsconfig.json

This PR aims to adapt the address and common toponym schemas to fit with the new standards : 
- switched "commonToponymID" key to "mainCommonToponymID"
- added "secondaryCommonToponymIDs
- switched "label" to "labels"
- transfered "parcels" into "meta" ( `meta : { cadastre : { ids: [...] } }` )
- added converter from bal position type (`fra`) to ban position type (`eng`)

Updated address and common toponym schemas

---

src/routes.ts

Fix : using the route /district/cog/:cog, response is an array of district as cog can be the same for multiples districts. As a correction, we now take the first district but we would need to handle this multiplicity in the future (or not use the cog anymore, but the district ID directly).

Fix get district from cog

---

src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-topo-to-ban-topo.test.ts.snap
src/bal-converter/helpers/bal-topo-to-ban-topo.ts
src/types/ban-types.d.ts

I. Context 
Currently, in id-fix, we are not making the distinction between a common toponym deducted from a BAL address line a common toponym explicitly described as a line (number 99999). As a consequence, id-fix were extracting the parcels and the geometry from the address line.
II. Enhancement
This PR aims to separate the processing between a deducted common toponym and an explicit common toponym. The parcels and the geometry data is ONLY taken from an explicit common toponym (number === 99999) and NOT for a deducted common toponym.

Modified get geometry for common toponyms

---

src/bal-converter/helpers/__snapshots__/bal-addr-to-ban-addr.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-topo-to-ban-topo.test.ts.snap
src/bal-converter/helpers/bal-addr-to-ban-addr.ts
src/bal-converter/helpers/bal-topo-to-ban-topo.ts
src/types/ban-generic-types.d.ts
src/types/ban-types.d.ts

This PR aims to NOT send to ban API useless information such as default values for : 
- "meta" : if no meta information, the "meta" field won't be sent anymore.
- "geometry" : for addresses, geometry is required but for common toponyms, it is not. As a consequence, the "geometry" field won't be sent anymore if no data (ONLY common toponyms)
- "suffix" : for addresses, if no suffix information, the "suffix" field won't be sent anymore.

Modified data schema for optional fields

---

README.md
package.json
script/init-bal-into-ban.ts

I. Context
In order to be able to initialized data from a BAL CSV into the BAN DB, this PR aims to add a cli script to read a local BAL CSV file and send it to ID-Fix processing. As a consequence, data is sent to BAN DB through the new BAN-ID APIs.
II. Enhancement
This PR adds the "initBALIntoBAN" cli script. To use it, use the command : 
`npm run initBALIntoBAN ${pathToBALCsv}`
(replace ${pathToBALCsv} by the path of the BAL CSV file to initialized)
example : 
`npm run initBALIntoBAN ${pathToBALCsv}`

Added init bal into ban script

---

src/bal-converter/helpers/bal-addr-to-ban-addr.ts
src/types/bal-types.d.ts
src/types/ban-types.d.ts

This PR is related to the following PR and has to wait for its validation : https://github.com/BaseAdresseNationale/ban-plateforme/pull/263
I. Context : 
The field `lieudit_complement_nom` is currently not handled is the ID-Fix BAL processing. 
II. Enhancements : 
This PR aims to handle the `lieudit_complement_nom` by adding a `labels` field to the addresses, conform to the BAN-ID data schemas on addresses
III. How to test : 
1- Download a BAL (csv) and make sure at least one of the address has a lieudit_complement_nom. If not, add it manually in the CSV and save it.
2- Use the initBALIntoBAN script on ID-Fix to push your BAL into the BAN.
3- Go in the PostgreSQL DB, on Addresses table and look for the address(es) that has(have) the lieudit_complement_nom.
4- Verify that the "labels" …

Added labels from bal lieudit_complement_nom on address schema

---

src/ban-api/index.ts
src/routes.ts

I. Context
We need to store the revision data (id and date) into the database when using id-fix.
II. Enhancement
This PR aims to add a district partial update (using newly added patch route) on "bal" meta field to add :
- idRevision <= `_id` field from the revision
- dateRevision <= `publishedAt` field from the revision

Added idRevision and dateRevision retrieval on bal district meta data

---

.gitignore
package-lock.json
package.json
src/middleware/auth.ts
src/routes.ts
src/utils/local-current-date.ts
src/utils/logger.ts

For a better understanding of what is happening when id-fix is in use, we need to implement a better log system.
This PR aims to add a new logger with the following behavior : 
- in "Dev" mode, the logs are printed into the console
- in "Production" mode, the logs are written into files in a "log" folder (at the root of the app)
For the production mode, the rotation strategy organizes log files in a "logs" directory, names them based on the date, archives them in a compressed format, limits the size of each log file to 20 megabytes, and retains log files for up to 14 days.

Added new logger with file rotation strategy

---

src/routes.ts

This pull request aims to rename the main id-fix route to something more relevant.
From `/district/cog/:cog` to `compute-from-cog/:cog`. To do the change progressively, the code of the route `/district/cog/:cog` has been duplicated to add the new route `compute-from-cog/:cog`
When ban-plateforme will use the new route `compute-from-cog/:cog` we need to deleted the old route `/district/cog/:cog`

Added compute-from-cog/ route as a duplication of /district/cog/ route

---

src/bal-converter/helpers/__snapshots__/check-if-bal-use-ban-id.test.ts.snap
src/bal-converter/helpers/check-if-bal-use-ban-id.test.ts
src/bal-converter/helpers/check-if-bal-use-ban-id.ts

On ID-Fix, we are checking the use of the ban-ID (to activate or not the id-fix processing) on a BAL thanks to some criteria. For now, we are checking if each line has a main common toponym ID. 
This PR aims to add a check on the BAL : 
- we check if there is a district ID on each line
- if a line is an address line (number different from 99_999), we check if there is an address ID

Added check on ban id use for address id

---

src/bal-converter/helpers/csv-bal-to-json-bal.ts

On id-fix, when converting a bal from csv to json, we slightly transform some values (parseInt, parseFloat, ...).
This PR adds a trim operation on all values from the BAL csv to solve empty string issues :

Added trim operation on all values from bal

---

src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/bal-topo-to-ban-topo.ts

Fix : id-fix was processing the BAL by putting a 'cadastre' meta on all common toponyms that have address numbers. This PR fix adds a condition to create a 'cadastre' meta : it has to be a BAL line with the 99_999 number to identify that it is a common toponym without number.

Fix cadastre meta on common toponym

---

src/bal-converter/helpers/__snapshots__/bal-addr-to-ban-addr.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-topo-to-ban-topo.test.ts.snap
src/bal-converter/helpers/bal-addr-to-ban-addr.ts
src/bal-converter/helpers/bal-to-ban.ts
src/bal-converter/helpers/bal-topo-to-ban-topo.ts

Id-fix is processing a BAL. In the BAL format, multiple lines can represent the same entity : 
- an address : in a multi-position case
- a common toponym : when there are multiple address on a same street. 
There was an issue in the code when generating a hash on an entity in a multi line case. As a matter of fact, the hash was generated taking into account the previous hash generated on the previous line. 
This PR solve the issue on the hash generation in a multi line case (multi position on a address and mutli lines that represent a common toponym)

Fix generate md5

---

src/bal-converter/helpers/csv-bal-to-json-bal.ts

When transforming the csv bal to a json bal, id-fix is processing the cad_parcelles so that : 
- the whole cad_parcelles cell is trimmed (example : `" 591183540AV0192 | 591183540AV0191 "` => `"591183540AV0192 | 591183540AV0191"`). 
- the resulted trimmed value is split by the pipe (= '|') separator to get an array of parcel ids (example : `"591183540AV0192 | 591183540AV0191"` => `["591183540AV0192 "," 591183540AV0191"]`
In this process, id-fix is not trimming again each of the array values.
This PR adds in the cad_parcelles processing from csv to json, the trimming of each value of the resulted parcel ids array.
In our example, it would result in : `["591183540AV0192 "," 591183540AV0191"]` => `["591183540AV0192","591183540AV0191"]`

Fixed cad_parcelles array by trimming each values

---

.env.sample
docker-compose.yml
package-lock.json
package.json
src/app.ts
src/mock.ts

Id-fix has a strong dependency on a `api-de-dépôt`.
This PR adds a `standalone` mode that is mocking the `api-de-dépôt` to be able to give a local BAL file. 
In order to do that, 
- a new boolean env parameter has been added : `STANDALONE_MODE` (=true/false),
- a new env parameter to target the BAL file : `PATH_TO_BAL_FILE` (absolute path from the root),
- the local BAL file has to be named `bal-${cog}.csv` (${cog} being the insee code of the desired BAL)

Added mock for dump api importing local file instead

---

src/bal-converter/helpers/bal-topo-to-ban-topo.ts

Dans la traduction de bal to ban, si l'élément est vide c'est qu'il n'existe pas : Ne pas le mettre dans le format ban.
lié avec le format/schema labelSchema ban-platform  lib/api/schema.js
exemple : https://plateforme-bal.adresse.data.gouv.fr/api-depot/revisions/668b98ef093891c55e5a3d92/files/bal/download
bal de bayonne ,
le Giratoire Saint-Bernard , banid_topo 20bbc4d0-bfa3-4cc7-b72b-ea3c92cdd419
possede un voie_libelle mais pas de voie_libelle_eus

pas de libelle vide dans ban topo

---

src/bal-converter/helpers/__snapshots__/validator.test.ts.snap
src/bal-converter/helpers/index.ts
src/bal-converter/helpers/validator.test.ts
src/bal-converter/helpers/validator.ts
src/compute-from-cog.ts

For reinforcing BAL controls, id-fix is making some checks when receiving a BAL
This PR adds checking rules on district ID : 
- Only 1 district ID in the received BAL. As a consequence, we ensure 1 BAL = 1 district ID = 1 cog 
- the district ID used in the BAL is the same as the district ID we have in our data base (so that we ensure that the district has the right to updates the addresses and toponyms linked to this district ID).

Added check rules for district ID consistency and rights

---

src/bal-converter/helpers/__snapshots__/bal-addr-to-ban-addr.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-to-ban.test.ts.snap
src/bal-converter/helpers/__snapshots__/bal-topo-to-ban-topo.test.ts.snap
src/bal-converter/helpers/bal-addr-to-ban-addr.ts
src/bal-converter/helpers/bal-topo-to-ban-topo.ts

Currently, the `cle_interop` data is not retrieved from bal file as not handled by ban-plateforme API
This PR adds : 
- the `cle_interop` in address bal meta as `cleInterop` key
- the `deprecatedID` (= `${inseeCode}_${code for street}`) in common toponym bal meta as `deprecatedID` key. The deprecated ID is corresponding to the two first parts of the `cle_interop`.

Added clef_interop bal data to address and common toponym bal meta

---

src/bal-converter/helpers/csv-bal-to-json-bal.ts

An UUID is not case sensitive. It is valid and equivalent either it is in lower case and in upper case.
This PR adds a formatting process when retrieving the ban ids from the BAL for the following columns : 
- id_ban_adresse
- id_ban_toponyme
- id_ban_commune

Added 'to lower case' processing when retrieving ban ids

---

src/bal-converter/helpers/__snapshots__/bal-addr-to-ban-addr.test.ts.snap
src/bal-converter/helpers/bal-addr-to-ban-addr.test.ts
src/bal-converter/helpers/bal-addr-to-ban-addr.ts

Currently, id-fix does not retrieve an adresse line that have a number equal to 0
This PR aims to accept and process an address that has a number equal to 0

Accepted address with number equal to 0
